name: Build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Build
        run: |
          GOOS=linux GOARCH=amd64 go build -o "lfm-cli-linux-amd64.${{  github.ref_name }}" -v ./...

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: builds
          path: lfm-cli-*