name: Build and Release

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Build
        run: |
          GOOS=darwin GOARCH=amd64 go build -o "lfm-cli-macos-amd64.${{  github.ref_name }}" -v ./...
          GOOS=darwin GOARCH=arm64 go build -o "lfm-cli-macos-arm64.${{  github.ref_name }}" -v ./...
          GOOS=windows GOARCH=amd64 go build -o "lfm-cli-windows-amd64.${{  github.ref_name }}.exe" -v ./...
          GOOS=linux GOARCH=amd64 go build -o "lfm-cli-linux-amd64.${{  github.ref_name }}" -v ./...

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: builds
          path: lfm-cli-*
