name: Build

on:
  push:
    tags:
      - v*
    branches:
      - release/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Build
        run: |
          GOOS=darwin GOARCH=amd64 go build -o "lfm2discord-cli-macos-amd64.${{  github.ref_name }}" -v ./...
          GOOS=darwin GOARCH=arm64 go build -o "lfm2discord-cli-macos-arm64.${{  github.ref_name }}" -v ./...
          GOOS=windows GOARCH=amd64 go build -o "lfm2discord-cli-windows-amd64.${{  github.ref_name }}.exe" -v ./...
          GOOS=linux GOARCH=amd64 go build -o "lfm2discord-cli-linux-amd64.${{  github.ref_name }}" -v ./...

      - name: Save as artifact
        uses: actions/upload-artifact@v2
        with:
          name: builds
          path: lfm2discord-cli-*

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Get artifact
        uses: actions/download-artifact@v3
        with:
          name: builds

      - name: Release Build
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          draft: true
          files: |
            lfm2discord-cli-*
